// This file was auto-generated by ML.NET Model Builder. 

using System;
using Microsoft.ML.Data;

namespace ML.IncidentAmountForecast.Regression.DataStructures
{
    public class ModelOutput
    {
        [ColumnName("Score")]
        public float ForecastedIncidents { get; set; }
    }
}
