// This file was auto-generated by ML.NET Model Builder. 

using System;
using Microsoft.ML.Data;

namespace ML.IncidentAmountForecast.SSA.Model
{
    public class ModelOutput
    {

        public float[] ForecastedIncidents { get; set; }

        public float[] LowerBoundIncidents { get; set; }

        public float[] UpperBoundIncidents { get; set; }
    }
}
